steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - app
      - deploy
      - app.yaml
      - "--quiet"
    dir: "." # deploy dari root folder

options:
  logging: CLOUD_LOGGING_ONLY
